<?php
/**
 * pb-split-guide — Marginalia icon set.
 *
 * Monochrome 24×24 SVG icons following the design philosophy in
 * docs/icons/ICON-DESIGN-PHILOSOPHY.md. All icons inherit colour
 * via `currentColor` and share the same stroke metrics.
 *
 * Generated by build_icons.py — do not edit by hand.
 *
 * @package PB_Split_Guide
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! class_exists( 'PBSG_Icons' ) ) {

    class PBSG_Icons {

        /**
         * Raw <svg> bodies keyed by icon name.
         *
         * @var array<string,string>
         */
        private static $bodies = array(
    'document' => '<rect x="5" y="3" width="14" height="18" rx="1.5"/> <line x1="8" y1="8"  x2="16" y2="8"/> <line x1="8" y1="12" x2="16" y2="12"/> <line x1="8" y1="16" x2="13" y2="16"/>',
    'document-page' => '<path d="M6 3h8l5 5v12a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1z"/> <path d="M14 3v5h5"/>',
    'document-multi' => '<rect x="3"  y="6" width="12" height="14" rx="1"/> <rect x="9"  y="4" width="12" height="14" rx="1"/>',
    'chart-bar' => '<line x1="4" y1="20" x2="20" y2="20"/> <rect x="6"  y="12" width="3" height="8"/> <rect x="11" y="7"  width="3" height="13"/> <rect x="16" y="15" width="3" height="5"/>',
    'disk' => '<rect x="4" y="4"  width="16" height="16" rx="2"/> <rect x="8" y="4"  width="8"  height="5"/> <rect x="7" y="13" width="10" height="7"/>',
    'image' => '<rect x="3" y="5" width="18" height="14" rx="1.5"/> <circle cx="8" cy="10" r="1.5"/> <path d="M3.5 17l3.5-3.5 3 3 4-4 6 5.5"/>',
    'video' => '<rect x="3" y="5" width="18" height="14" rx="1.5"/> <path d="M10 9v6l5-3z"/>',
    'audio' => '<path d="M9 18V6l10-2v12"/> <circle cx="7"  cy="18" r="2"/> <circle cx="17" cy="16" r="2"/>',
    'package' => '<path d="M3 7l9-4 9 4v10l-9 4-9-4z"/> <path d="M3 7l9 4 9-4"/> <line x1="12" y1="11" x2="12" y2="21"/>',
    'chevron-down' => '<path d="M6 9l6 6 6-6"/>',
    'chevron-right' => '<path d="M9 6l6 6-6 6"/>',
    'play' => '<circle cx="12" cy="12" r="9"/> <path d="M10 8.5v7l6-3.5z"/>',
    'arrow-horizontal' => '<line x1="3" y1="12" x2="21" y2="12"/> <path d="M7 8l-4 4 4 4"/> <path d="M17 8l4 4-4 4"/>',
    'arrow-up' => '<line x1="12" y1="20" x2="12" y2="4"/> <path d="M6 10l6-6 6 6"/>',
    'arrow-down' => '<line x1="12" y1="4" x2="12" y2="20"/> <path d="M6 14l6 6 6-6"/>',
    'arrow-up-right' => '<line x1="6" y1="18" x2="18" y2="6"/> <path d="M8 6h10v10"/>',
    'check' => '<path d="M4.5 12.5l5 5 10-10"/>',
    'close' => '<line x1="6"  y1="6"  x2="18" y2="18"/> <line x1="18" y1="6"  x2="6"  y2="18"/>',
    'warning' => '<path d="M12 4l10 17H2z"/> <line x1="12" y1="10" x2="12" y2="14"/> <circle cx="12" cy="17.5" r="0.6" fill="currentColor" stroke="none"/>',
    'link' => '<path d="M10.5 13.5a4 4 0 0 1 0-5.5l3-3a4 4 0 0 1 5.5 5.5l-1.5 1.5"/> <path d="M13.5 10.5a4 4 0 0 1 0 5.5l-3 3a4 4 0 0 1-5.5-5.5l1.5-1.5"/>',
    'globe' => '<circle cx="12" cy="12" r="9"/> <line x1="3" y1="12" x2="21" y2="12"/> <path d="M12 3c2.8 3 4.2 6.6 4.2 9s-1.4 6-4.2 9c-2.8-3-4.2-6.6-4.2-9s1.4-6 4.2-9z"/>',
    'drag-handle' => '<circle cx="9"  cy="6"  r="1.1" fill="currentColor" stroke="none"/> <circle cx="9"  cy="12" r="1.1" fill="currentColor" stroke="none"/> <circle cx="9"  cy="18" r="1.1" fill="currentColor" stroke="none"/> <circle cx="15" cy="6"  r="1.1" fill="currentColor" stroke="none"/> <circle cx="15" cy="12" r="1.1" fill="currentColor" stroke="none"/> <circle cx="15" cy="18" r="1.1" fill="currentColor" stroke="none"/>',
    'menu' => '<line x1="4" y1="7"  x2="20" y2="7"/> <line x1="4" y1="12" x2="20" y2="12"/> <line x1="4" y1="17" x2="20" y2="17"/>',
    'pencil' => '<path d="M16 3.5l4.5 4.5-11 11H5v-4.5z"/> <line x1="13" y1="6.5" x2="17.5" y2="11"/>',
    'puzzle' => '<path d="M4 5a1 1 0 0 1 1-1h5v1.5a1.5 1.5 0 0 0 3 0V4h5a1 1 0 0 1 1 1v5h-1.5a1.5 1.5 0 0 0 0 3H19v5a1 1 0 0 1-1 1h-5v-1.5a1.5 1.5 0 0 0-3 0V20H5a1 1 0 0 1-1-1v-5h1.5a1.5 1.5 0 0 0 0-3H4z"/>',
    'book-open' => '<path d="M3 5h6a3 3 0 0 1 3 3v12a2 2 0 0 0-2-2H3z"/> <path d="M21 5h-6a3 3 0 0 0-3 3v12a2 2 0 0 1 2-2h7z"/>',
    'shuffle' => '<path d="M16 4h4v4"/> <path d="M4 20l6-6"/> <path d="M14 10l6-6"/> <path d="M4 4l6 6"/> <path d="M14 14l6 6"/> <path d="M16 20h4v-4"/>',
    'lock-closed' => '<rect x="5" y="11" width="14" height="10" rx="1.5"/> <path d="M8 11V7a4 4 0 0 1 8 0v4"/>',
    'lock-open' => '<rect x="5" y="11" width="14" height="10" rx="1.5"/> <path d="M8 11V7a4 4 0 0 1 7-2.5"/>',
    'checkbox-multi' => '<rect x="4" y="4" width="16" height="16" rx="2"/> <path d="M8 12l3 3 5-6"/>',
    'radio' => '<circle cx="12" cy="12" r="9"/> <circle cx="12" cy="12" r="3.5" fill="currentColor" stroke="none"/>',
    'lightbulb' => '<path d="M9 15a5 5 0 1 1 6 0c-.7.5-1 1.3-1 2H10c0-.7-.3-1.5-1-2z"/> <line x1="9.5" y1="19" x2="14.5" y2="19"/> <line x1="10.5" y1="21.5" x2="13.5" y2="21.5"/>',
    'stopwatch' => '<circle cx="12" cy="14" r="7"/> <line x1="12" y1="14" x2="12" y2="9"/> <line x1="10" y1="3" x2="14" y2="3"/> <line x1="12" y1="3" x2="12" y2="6"/> <line x1="19" y1="7" x2="21" y2="5"/>',
    'clipboard' => '<rect x="5" y="5" width="14" height="16" rx="1.5"/> <rect x="9" y="3" width="6"  height="4"  rx="1"/> <line x1="9" y1="12" x2="15" y2="12"/> <line x1="9" y1="16" x2="13" y2="16"/>',
    'thumbs-up' => '<path d="M4 11h3v10H5a1 1 0 0 1-1-1z"/> <path d="M7 11l4-7a2 2 0 0 1 3 1v4h5a2 2 0 0 1 2 2.3l-1.5 7.3A2 2 0 0 1 17.5 20H7"/>',
    'refresh' => '<path d="M4 12a8 8 0 0 1 14-5.3"/> <path d="M20 3v5h-5"/> <path d="M20 12a8 8 0 0 1-14 5.3"/> <path d="M4 21v-5h5"/>',
    'maximize'    => '<path d="M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5"/>',
        );

        /**
         * Return a complete inline <svg> for the named icon.
         *
         * @param string $name   Icon name (e.g. 'lock-closed').
         * @param string $extra  Optional extra CSS class(es).
         * @return string        Inline SVG, or empty string if unknown.
         */
        public static function get( $name, $extra = '' ) {
            if ( ! isset( self::$bodies[ $name ] ) ) {
                return '';
            }

            $classes = 'pbsg-icon pbsg-icon--' . $name;
            if ( $extra ) {
                $classes .= ' ' . $extra;
            }

            return sprintf(
                '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" '
                . 'fill="none" stroke="currentColor" stroke-width="1.5" '
                . 'stroke-linecap="round" stroke-linejoin="round" '
                . 'aria-hidden="true" focusable="false" class="%s">%s</svg>',
                esc_attr( $classes ),
                self::$bodies[ $name ]
            );
        }

        /**
         * Return all icon names (useful for tests / docs).
         *
         * @return string[]
         */
        public static function names() {
            return array_keys( self::$bodies );
        }
    }
}

if ( ! function_exists( 'pbsg_icon' ) ) {
    /**
     * Shortcut to PBSG_Icons::get().
     *
     * @param string $name  Icon name.
     * @param string $extra Optional extra CSS class(es).
     * @return string       Inline SVG.
     */
    function pbsg_icon( $name, $extra = '' ) {
        return PBSG_Icons::get( $name, $extra );
    }
}
